version: '3.8'
services:
    web:
        hostname: secret-vault-web
        build: .
        ports:
            - '3000:3000'
        env_file:
            - .env
    postgres:
        hostname: secret-vault-postgres
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=Pass!2022
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./sql/initScripts.sql:/docker-entrypoint-initdb.d/initScripts.sql
            - ./sql/insertScripts.sql:/docker-entrypoint-initdb.d/insertScripts.sql
            - ./postgres_data/:/var/lib/postgresql/data
    pgadmin:
        hostname: secret-vault-pgadmin
        image: dpage/pgadmin4
        ports:
            - '5050:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=my-pg@admin.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
