version: '3.8'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            - PG_HOST=secret-vault-postgres-1
            - PG_PORT=5432
            - PG_DATABASE=postgres
            - PG_USER=postgres
            - PG_PASSWORD=Pass!2022
            - AES_KEY=AES!2022
            - SECRET_PREFIX=00000001
            - ENV_PREFIX=00000002
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=Pass!2022
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./sql/initScripts.sql:/docker-entrypoint-initdb.d/initScripts.sql
            - ./sql/insertScripts.sql:/docker-entrypoint-initdb.d/insertScripts.sql
            - ./postgres_data/:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - '5050:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=my-pg@admin.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
